version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root          # Contraseña del usuario root
      MYSQL_USER: user                   # Usuario adicional
      MYSQL_DATABASE: my_database        # Base de datos inicial
      MYSQL_PASSWORD: root               # Contraseña del usuario adicional
    ports:
      - "3306:3306"                      # Exponer el puerto de MySQL
    volumes:
      - db_data:/var/lib/mysql           # Persistir datos en un volumen
      - ./mysql-config:/etc/mysql/conf.d # Configuración personalizada de MySQL
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db                       # Vincular phpMyAdmin al servicio 'db'
      PMA_USER: root                     # Usuario por defecto
      PMA_PASSWORD: root                 # Contraseña por defecto
      UPLOAD_LIMIT: 128M                 # Configuración adicional
    ports:
      - "8091:80"                        # Exponer phpMyAdmin en el puerto 8091
    volumes:
      - ./php-config:/usr/local/etc/php/conf.d # Configuración personalizada de PHP
    networks:
      - db_network

volumes:
  db_data:                               # Volumen para almacenar datos de MySQL

networks:
  db_network:
    driver: bridge                       # Crear una red para los contenedores